import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Iframe from 'react-iframe'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script 
    type="module"
    src="https://gradio.s3-us-west-2.amazonaws.com/3.16.2/gradio.js">
</script>
      </Head>
     <iframe
    src="https://mrcuddle-lora.hf.space"
       width="100%"
      height="100%"
      scrolling="no"
      frameBorder="0"
></iframe>
          
    </>
  )
}
